<?php

namespace ContainerPOSxz9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rcb1QkIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rcb1QkI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rcb1QkI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'burgerRepository' => ['privates', 'App\\Repository\\BurgerRepository', 'getBurgerRepositoryService', true],
            'decoder' => ['privates', 'serializer', 'getSerializerService', false],
            'denormalizer' => ['privates', 'serializer', 'getSerializerService', false],
            'menuRepository' => ['privates', 'App\\Repository\\MenuRepository', 'getMenuRepositoryService', true],
            'portionFritesRepository' => ['privates', 'App\\Repository\\PortionFritesRepository', 'getPortionFritesRepositoryService', true],
            'tailleRepository' => ['privates', 'App\\Repository\\TailleRepository', 'getTailleRepositoryService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'burgerRepository' => 'App\\Repository\\BurgerRepository',
            'decoder' => '?',
            'denormalizer' => '?',
            'menuRepository' => 'App\\Repository\\MenuRepository',
            'portionFritesRepository' => 'App\\Repository\\PortionFritesRepository',
            'tailleRepository' => 'App\\Repository\\TailleRepository',
            'tokenStorage' => '?',
        ]);
    }
}
