<?php

namespace ContainerPOSxz9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q4IKjWqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q4IKjWq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q4IKjWq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.q4IKjWq.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.q4IKjWq": it references class "App\\Entity\\Produit" but no such service exists.'],
        ], [
            'data' => 'App\\Entity\\Produit',
        ]);
    }
}
