<?php

namespace ContainerPOSxz9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4RG02caService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4RG02ca' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4RG02ca'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'JWTManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'mailer' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'JWTManager' => '?',
            'hasher' => '?',
            'mailer' => 'App\\Service\\MailerService',
            'serializer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'validator' => '?',
        ]);
    }
}
