<?php

namespace ContainerPOSxz9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuInputDataTransformerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataTransformer\MenuInputDataTransformer' shared autowired service.
     *
     * @return \App\DataTransformer\MenuInputDataTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataTransformer/DataTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataTransformer/MenuInputDataTransformer.php';

        return $container->privates['App\\DataTransformer\\MenuInputDataTransformer'] = new \App\DataTransformer\MenuInputDataTransformer(($container->privates['validator'] ?? $container->getValidatorService()));
    }
}
