<?php

namespace ContainerPOSxz9X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOthersDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataProvider\OthersDataProvider' shared autowired service.
     *
     * @return \App\DataProvider\OthersDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataProvider/OthersDataProvider.php';

        return $container->privates['App\\DataProvider\\OthersDataProvider'] = new \App\DataProvider\OthersDataProvider(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
