<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Zone extends \App\Entity\Zone implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'montantLivraison', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'isEtat', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'quartiers', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'commandes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'montantLivraison', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'isEtat', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'quartiers', '' . "\0" . 'App\\Entity\\Zone' . "\0" . 'commandes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Zone $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle(string $libelle): \App\Entity\Zone
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsEtat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsEtat', []);

        return parent::isIsEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEtat(bool $isEtat): \App\Entity\Zone
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEtat', [$isEtat]);

        return parent::setIsEtat($isEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuartiers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuartiers', []);

        return parent::getQuartiers();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuartier(\App\Entity\Quartier $quartier): \App\Entity\Zone
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuartier', [$quartier]);

        return parent::addQuartier($quartier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuartier(\App\Entity\Quartier $quartier): \App\Entity\Zone
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuartier', [$quartier]);

        return parent::removeQuartier($quartier);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantLivraison(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantLivraison', []);

        return parent::getMontantLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantLivraison(float $montantLivraison): \App\Entity\Zone
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantLivraison', [$montantLivraison]);

        return parent::setMontantLivraison($montantLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', []);

        return parent::getCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\App\Entity\Commande $commande): \App\Entity\Zone
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', [$commande]);

        return parent::addCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\App\Entity\Commande $commande): \App\Entity\Zone
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', [$commande]);

        return parent::removeCommande($commande);
    }

}
