<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PortionFrites extends \App\Entity\PortionFrites implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'App\\Entity\\PortionFrites' . "\0" . 'menu', '' . "\0" . 'App\\Entity\\PortionFrites' . "\0" . 'menuPortionFrites', '' . "\0" . 'App\\Entity\\PortionFrites' . "\0" . 'commandePortionFrites', 'nom', 'image', 'prix', 'file', 'isEtat'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'App\\Entity\\PortionFrites' . "\0" . 'menu', '' . "\0" . 'App\\Entity\\PortionFrites' . "\0" . 'menuPortionFrites', '' . "\0" . 'App\\Entity\\PortionFrites' . "\0" . 'commandePortionFrites', 'nom', 'image', 'prix', 'file', 'isEtat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PortionFrites $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMenu(): ?\App\Entity\Menu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenu', []);

        return parent::getMenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenu(?\App\Entity\Menu $menu): \App\Entity\PortionFrites
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenu', [$menu]);

        return parent::setMenu($menu);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuPortionFrites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuPortionFrites', []);

        return parent::getMenuPortionFrites();
    }

    /**
     * {@inheritDoc}
     */
    public function addMenuPortionFrite(\App\Entity\MenuPortionFrites $menuPortionFrite): \App\Entity\PortionFrites
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMenuPortionFrite', [$menuPortionFrite]);

        return parent::addMenuPortionFrite($menuPortionFrite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMenuPortionFrite(\App\Entity\MenuPortionFrites $menuPortionFrite): \App\Entity\PortionFrites
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMenuPortionFrite', [$menuPortionFrite]);

        return parent::removeMenuPortionFrite($menuPortionFrite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandePortionFrites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandePortionFrites', []);

        return parent::getCommandePortionFrites();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommandePortionFrite(\App\Entity\CommandePortionFrites $commandePortionFrite): \App\Entity\PortionFrites
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommandePortionFrite', [$commandePortionFrite]);

        return parent::addCommandePortionFrite($commandePortionFrite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommandePortionFrite(\App\Entity\CommandePortionFrites $commandePortionFrite): \App\Entity\PortionFrites
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommandePortionFrite', [$commandePortionFrite]);

        return parent::removeCommandePortionFrite($commandePortionFrite);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsEtat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsEtat', []);

        return parent::isIsEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEtat(bool $isEtat): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEtat', [$isEtat]);

        return parent::setIsEtat($isEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile(): ?object
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(?object $file): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

}
