<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BoissonTaille extends \App\Entity\BoissonTaille implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'quantiteStock', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'isEtat', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'boisson', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'commandeMenuBoissonTailles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'id', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'quantiteStock', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'isEtat', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'boisson', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\BoissonTaille' . "\0" . 'commandeMenuBoissonTailles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BoissonTaille $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantiteStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantiteStock', []);

        return parent::getQuantiteStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantiteStock(int $quantiteStock): \App\Entity\BoissonTaille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantiteStock', [$quantiteStock]);

        return parent::setQuantiteStock($quantiteStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(string $etat): \App\Entity\BoissonTaille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsEtat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsEtat', []);

        return parent::isIsEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEtat(bool $isEtat): \App\Entity\BoissonTaille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEtat', [$isEtat]);

        return parent::setIsEtat($isEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoisson(): ?\App\Entity\Boisson
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoisson', []);

        return parent::getBoisson();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoisson(?\App\Entity\Boisson $boisson): \App\Entity\BoissonTaille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoisson', [$boisson]);

        return parent::setBoisson($boisson);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaille(): ?\App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaille', []);

        return parent::getTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaille(?\App\Entity\Taille $taille): \App\Entity\BoissonTaille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaille', [$taille]);

        return parent::setTaille($taille);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandeMenuBoissonTailles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandeMenuBoissonTailles', []);

        return parent::getCommandeMenuBoissonTailles();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommandeMenuBoissonTaille(\App\Entity\CommandeMenuBoissonTaille $commandeMenuBoissonTaille): \App\Entity\BoissonTaille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommandeMenuBoissonTaille', [$commandeMenuBoissonTaille]);

        return parent::addCommandeMenuBoissonTaille($commandeMenuBoissonTaille);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommandeMenuBoissonTaille(\App\Entity\CommandeMenuBoissonTaille $commandeMenuBoissonTaille): \App\Entity\BoissonTaille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommandeMenuBoissonTaille', [$commandeMenuBoissonTaille]);

        return parent::removeCommandeMenuBoissonTaille($commandeMenuBoissonTaille);
    }

}
