<?php

namespace ContainerKybtPfs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mj9omN_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mj9omN.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mj9omN.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BoissonController::__invoke' => ['privates', '.service_locator.Ntb2FG_', 'get_ServiceLocator_Ntb2FGService', true],
            'App\\Controller\\CommandeAction::__invoke' => ['privates', '.service_locator.hybaK61', 'get_ServiceLocator_HybaK61Service', true],
            'App\\Controller\\EditProduitAction::__invoke' => ['privates', '.service_locator.q4IKjWq', 'get_ServiceLocator_Q4IKjWqService', true],
            'App\\Controller\\MenuController::__invoke' => ['privates', '.service_locator.Rcb1QkI', 'get_ServiceLocator_Rcb1QkIService', true],
            'App\\Controller\\MenuController::addForMenu' => ['privates', '.service_locator.IZkUT2m', 'get_ServiceLocator_IZkUT2mService', true],
            'App\\Controller\\MenuController::removeForMenu' => ['privates', '.service_locator.jHQ_2RK', 'get_ServiceLocator_JHQ2RKService', true],
            'App\\Controller\\RegistrationsController::__invoke' => ['privates', '.service_locator.4RG02ca', 'get_ServiceLocator_4RG02caService', true],
            'App\\Controller\\VerifyEmailAction::__invoke' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\BoissonController:__invoke' => ['privates', '.service_locator.Ntb2FG_', 'get_ServiceLocator_Ntb2FGService', true],
            'App\\Controller\\BoissonController' => ['privates', '.service_locator.Ntb2FG_', 'get_ServiceLocator_Ntb2FGService', true],
            'App\\Controller\\CommandeAction:__invoke' => ['privates', '.service_locator.hybaK61', 'get_ServiceLocator_HybaK61Service', true],
            'App\\Controller\\CommandeAction' => ['privates', '.service_locator.hybaK61', 'get_ServiceLocator_HybaK61Service', true],
            'App\\Controller\\EditProduitAction:__invoke' => ['privates', '.service_locator.q4IKjWq', 'get_ServiceLocator_Q4IKjWqService', true],
            'App\\Controller\\EditProduitAction' => ['privates', '.service_locator.q4IKjWq', 'get_ServiceLocator_Q4IKjWqService', true],
            'App\\Controller\\MenuController:__invoke' => ['privates', '.service_locator.Rcb1QkI', 'get_ServiceLocator_Rcb1QkIService', true],
            'App\\Controller\\MenuController' => ['privates', '.service_locator.Rcb1QkI', 'get_ServiceLocator_Rcb1QkIService', true],
            'App\\Controller\\MenuController:addForMenu' => ['privates', '.service_locator.IZkUT2m', 'get_ServiceLocator_IZkUT2mService', true],
            'App\\Controller\\MenuController:removeForMenu' => ['privates', '.service_locator.jHQ_2RK', 'get_ServiceLocator_JHQ2RKService', true],
            'App\\Controller\\RegistrationsController:__invoke' => ['privates', '.service_locator.4RG02ca', 'get_ServiceLocator_4RG02caService', true],
            'App\\Controller\\RegistrationsController' => ['privates', '.service_locator.4RG02ca', 'get_ServiceLocator_4RG02caService', true],
            'App\\Controller\\VerifyEmailAction:__invoke' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\VerifyEmailAction' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\BoissonController::__invoke' => '?',
            'App\\Controller\\CommandeAction::__invoke' => '?',
            'App\\Controller\\EditProduitAction::__invoke' => '?',
            'App\\Controller\\MenuController::__invoke' => '?',
            'App\\Controller\\MenuController::addForMenu' => '?',
            'App\\Controller\\MenuController::removeForMenu' => '?',
            'App\\Controller\\RegistrationsController::__invoke' => '?',
            'App\\Controller\\VerifyEmailAction::__invoke' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BoissonController:__invoke' => '?',
            'App\\Controller\\BoissonController' => '?',
            'App\\Controller\\CommandeAction:__invoke' => '?',
            'App\\Controller\\CommandeAction' => '?',
            'App\\Controller\\EditProduitAction:__invoke' => '?',
            'App\\Controller\\EditProduitAction' => '?',
            'App\\Controller\\MenuController:__invoke' => '?',
            'App\\Controller\\MenuController' => '?',
            'App\\Controller\\MenuController:addForMenu' => '?',
            'App\\Controller\\MenuController:removeForMenu' => '?',
            'App\\Controller\\RegistrationsController:__invoke' => '?',
            'App\\Controller\\RegistrationsController' => '?',
            'App\\Controller\\VerifyEmailAction:__invoke' => '?',
            'App\\Controller\\VerifyEmailAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
