<?php

namespace ContainerKybtPfs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ntb2FGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ntb2FG_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ntb2FG_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'boissonRepository' => ['privates', 'App\\Repository\\BoissonRepository', 'getBoissonRepositoryService', true],
            'decoder' => ['privates', 'serializer', 'getSerializerService', false],
            'denormalizer' => ['privates', 'serializer', 'getSerializerService', false],
            'tailleRepository' => ['privates', 'App\\Repository\\TailleRepository', 'getTailleRepositoryService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'boissonRepository' => 'App\\Repository\\BoissonRepository',
            'decoder' => '?',
            'denormalizer' => '?',
            'tailleRepository' => 'App\\Repository\\TailleRepository',
            'tokenStorage' => '?',
        ]);
    }
}
