<?php

namespace ContainerKybtPfs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductDataPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\ProductDataPersister' shared autowired service.
     *
     * @return \App\DataPersister\ProductDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersister/ProductDataPersister.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileUploaderService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CalculPrixMenu.php';

        return $container->privates['App\\DataPersister\\ProductDataPersister'] = new \App\DataPersister\ProductDataPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), new \App\Service\FileUploaderService(), new \App\Service\CalculPrixMenu());
    }
}
