<?php

namespace ContainerKybtPfs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceEntityRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IZkUT2m.Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IZkUT2m": it references class "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository" but no such service exists. You should maybe alias this class to one of these existing services: "App\\Repository\\BoissonRepository", "App\\Repository\\BoissonTailleRepository", "App\\Repository\\BurgerRepository", "App\\Repository\\CatalogueRepository", "App\\Repository\\ClientRepository", "App\\Repository\\CommandeBoissonTailleRepository", "App\\Repository\\CommandeBurgerRepository", "App\\Repository\\CommandeMenuBoissonTailleRepository", "App\\Repository\\CommandeMenuRepository", "App\\Repository\\CommandePortionFritesRepository", "App\\Repository\\CommandeProduitRepository", "App\\Repository\\CommandeRepository", "App\\Repository\\CommandeTailleRepository", "App\\Repository\\ComplementRepository", "App\\Repository\\ImageRepository", "App\\Repository\\LivraisonRepository", "App\\Repository\\LivreurRepository", "App\\Repository\\MenuBoissonTailleRepository", "App\\Repository\\MenuBurgerRepository", "App\\Repository\\MenuPortionFritesRepository", "App\\Repository\\MenuRepository", "App\\Repository\\MenuTailleRepository", "App\\Repository\\PortionFritesRepository", "App\\Repository\\ProduitRepository", "App\\Repository\\QuartierRepository", "App\\Repository\\TailleRepository", "App\\Repository\\UserRepository", "App\\Repository\\ZoneRepository".');
    }
}
