<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPOSxz9X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPOSxz9X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPOSxz9X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPOSxz9X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPOSxz9X\App_KernelDevDebugContainer([
    'container.build_hash' => 'POSxz9X',
    'container.build_id' => '1a778640',
    'container.build_time' => 1657615908,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPOSxz9X');
